// examples/react-native/src/App.tsx
/**
 * @rasenjs/react-native example — App component (TSX)
 *
 * JSX syntax via automatic runtime. Babel compiles to `import { jsx } from 'react/jsx-runtime'`,
 * which Metro resolves to `@rasenjs/react-native/jsx-runtime` via extraNodeModules.
 */

import { View, Text, TouchableOpacity, each, when } from '@rasenjs/react-native'
import { ref, computed } from '@vue/reactivity'
import { useReactiveRuntime } from '@rasenjs/reactive-vue'

useReactiveRuntime()

const counter = ref(0)
const isDark = ref(false)

const todos = ref([
  { id: 1, text: 'Learn Rasen', done: true },
  { id: 2, text: 'Build an app', done: false },
  { id: 3, text: 'Ship to production', done: false },
])

const theme = computed(() => ({
  bg: isDark.value ? '#1a1a2e' : '#f5f5f7',
  surface: isDark.value ? '#2a2a3e' : '#ffffff',
  text: isDark.value ? '#e0e0ee' : '#1a1a2e',
  accent: isDark.value ? '#16c79a' : '#0a8c6a',
}))

const todoStats = computed(() => {
  const total = todos.value.length
  const done = todos.value.filter(t => t.done).length
  return done + '/' + total + ' done'
})

const toggleTodo = (id: number) => {
  todos.value = todos.value.map(t =>
    t.id === id ? { ...t, done: !t.done } : t
  )
}

const CounterSection = () => (
  <View style={() => ({
    backgroundColor: theme.value.surface,
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    alignItems: 'center',
  })}>
    <Text style={{ fontSize: 14, color: '#888', marginBottom: 4 }}>
      REACTIVE COUNTER
    </Text>
    <Text style={() => ({
      fontSize: 48,
      fontWeight: 'bold',
      color: theme.value.accent,
      marginVertical: 12,
    })}>
      {counter}
    </Text>
    <View style={{ flexDirection: 'row' }}>
      <TouchableOpacity
        style={{ backgroundColor: '#16c79a', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8, marginRight: 12 }}
        onTouchEnd={() => { counter.value++ }}
      >
        <Text style={{ color: 'white', fontSize: 18, fontWeight: 'bold' }}>+</Text>
      </TouchableOpacity>
      <TouchableOpacity
        style={{ backgroundColor: '#e74c3c', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8 }}
        onTouchEnd={() => { counter.value-- }}
      >
        <Text style={{ color: 'white', fontSize: 18, fontWeight: 'bold' }}>{'\u2212'}</Text>
      </TouchableOpacity>
    </View>
  </View>
)

const TodoSection = () => (
  <View style={() => ({
    backgroundColor: theme.value.surface,
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
  })}>
    <Text style={{ fontSize: 14, color: '#888', marginBottom: 4 }}>TODO LIST</Text>
    <Text style={() => ({ fontSize: 12, color: theme.value.accent, marginBottom: 12 })}>
      {todoStats}
    </Text>
    {each(todos, (todo) => (
      <View style={{ flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#eee' }}>
        <TouchableOpacity
          onPress={() => toggleTodo(todo.id)}
          style={{ width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: todo.done ? '#4CAF50' : '#ccc', backgroundColor: todo.done ? '#4CAF50' : 'transparent', marginRight: 12, justifyContent: 'center', alignItems: 'center' }}
        >
          <Text style={{ color: 'white', fontSize: 14, fontWeight: 'bold' }}>
            {todo.done ? '\u2713' : ''}
          </Text>
        </TouchableOpacity>
        <Text style={() => ({ flex: 1, fontSize: 16, color: todo.done ? '#999' : theme.value.text, textDecorationLine: todo.done ? 'line-through' : 'none' })}>
          {todo.text}
        </Text>
      </View>
    ))}
  </View>
)

const ConditionalSection = () => (
  <View style={{ marginBottom: 16 }}>
    {when({
      condition: () => counter.value > 0,
      then: () => (
        <View style={() => ({ backgroundColor: theme.value.surface, borderRadius: 12, padding: 20, alignItems: 'center' })}>
          {when({
            condition: () => counter.value > 5,
            then: () => <Text style={{ fontSize: 16, color: '#e74c3c', fontWeight: 'bold' }}>{'\u26A0\uFE0F Counter is high!'}</Text>,
            else: () => <Text style={() => ({ fontSize: 16, color: theme.value.accent })}>Counter is {counter.value}</Text>,
          })}
        </View>
      ),
    })}
  </View>
)

const ThemeToggle = () => (
  <TouchableOpacity
    style={() => ({ backgroundColor: theme.value.accent, paddingVertical: 14, borderRadius: 8, alignItems: 'center', marginBottom: 16 })}
    onTouchEnd={() => { isDark.value = !isDark.value }}
  >
    <Text style={{ color: 'white', fontSize: 16, fontWeight: 'bold' }}>
      {() => isDark.value ? '\u2600\uFE0F Light Mode' : '\uD83C\uDF19 Dark Mode'}
    </Text>
  </TouchableOpacity>
)

export const App = () => (
  <View style={() => ({ flex: 1, backgroundColor: theme.value.bg, paddingTop: 60, paddingHorizontal: 20 })}>
    <Text style={() => ({ fontSize: 28, fontWeight: 'bold', color: theme.value.text, marginBottom: 20 })}>
      {'\u26A1 Rasen RN'}
    </Text>
    <CounterSection />
    <TodoSection />
    <ConditionalSection />
    <ThemeToggle />
  </View>
)

// examples/react-native/src/App.ts
/**
 * Rasen React Native Example App
 *
 * This demonstrates using Rasen's reactive rendering with React Native's
 * Fabric architecture, bypassing React's reconciler.
 */

import { setReactiveRuntime } from '@rasenjs/core';
import { createVueRuntime } from '@rasenjs/reactive-vue';
import { ref, type Ref } from 'vue';
import {
  view,
  text,
  textInput,
  touchableOpacity,
  scrollView,
  mount,
  type RNMountFunction
} from '@rasenjs/react-native';

// Create and set Vue reactive runtime
setReactiveRuntime(createVueRuntime());

// Type alias for Todo item
interface TodoItem {
  id: number;
  text: string;
  done: boolean;
}

/**
 * Counter Example Component
 */
function CounterExample(): RNMountFunction {
  const count: Ref<number> = ref(0);

  return view({
    style: {
      padding: 20,
      backgroundColor: '#f5f5f5',
      borderRadius: 10,
      marginBottom: 20,
    },
    children: [
      text({
        style: {
          fontSize: 24,
          fontWeight: 'bold',
          marginBottom: 10,
          color: '#333',
        },
        children: 'Counter Example',
      }),
      text({
        style: {
          fontSize: 48,
          textAlign: 'center',
          marginVertical: 20,
          color: '#2196F3',
        },
        children: () => `${count.value}`,
      }),
      view({
        style: {
          flexDirection: 'row',
          justifyContent: 'center',
          gap: 10,
        },
        children: [
          touchableOpacity({
            onPress: () => count.value--,
            style: {
              backgroundColor: '#f44336',
              paddingHorizontal: 30,
              paddingVertical: 15,
              borderRadius: 8,
            },
            children: text({
              style: { color: 'white', fontSize: 24, fontWeight: 'bold' },
              children: '-',
            }),
          }),
          touchableOpacity({
            onPress: () => count.value++,
            style: {
              backgroundColor: '#4CAF50',
              paddingHorizontal: 30,
              paddingVertical: 15,
              borderRadius: 8,
            },
            children: text({
              style: { color: 'white', fontSize: 24, fontWeight: 'bold' },
              children: '+',
            }),
          }),
        ],
      }),
    ],
  });
}

/**
 * Todo List Example Component
 */
function TodoExample(): RNMountFunction {
  const todos: Ref<TodoItem[]> = ref([
    { id: 1, text: 'Learn Rasen', done: false },
    { id: 2, text: 'Build an app', done: false },
  ]);
  const inputText: Ref<string> = ref('');
  let nextId = 3;

  const addTodo = () => {
    if (inputText.value.trim()) {
      todos.value = [...todos.value, { id: nextId++, text: inputText.value, done: false }];
      inputText.value = '';
    }
  };

  const toggleTodo = (id: number) => {
    todos.value = todos.value.map((todo: TodoItem) =>
      todo.id === id ? { ...todo, done: !todo.done } : todo
    );
  };

  const removeTodo = (id: number) => {
    todos.value = todos.value.filter((todo: TodoItem) => todo.id !== id);
  };

  return view({
    style: {
      padding: 20,
      backgroundColor: '#e3f2fd',
      borderRadius: 10,
      marginBottom: 20,
    },
    children: [
      text({
        style: {
          fontSize: 24,
          fontWeight: 'bold',
          marginBottom: 10,
          color: '#1565C0',
        },
        children: 'Todo List',
      }),
      view({
        style: {
          flexDirection: 'row',
          marginBottom: 15,
        },
        children: [
          textInput({
            value: () => inputText.value,
            onChangeText: (newText: string) => {
              inputText.value = newText;
            },
            placeholder: 'Add a new todo...',
            style: {
              flex: 1,
              borderWidth: 1,
              borderColor: '#90CAF9',
              borderRadius: 8,
              paddingHorizontal: 15,
              paddingVertical: 10,
              fontSize: 16,
              backgroundColor: 'white',
            },
          }),
          touchableOpacity({
            onPress: addTodo,
            style: {
              backgroundColor: '#2196F3',
              paddingHorizontal: 20,
              paddingVertical: 10,
              borderRadius: 8,
              marginLeft: 10,
              justifyContent: 'center',
            },
            children: text({
              style: { color: 'white', fontSize: 16, fontWeight: 'bold' },
              children: 'Add',
            }),
          }),
        ],
      }),
      // Todo items - using reactive children
      view({
        style: { gap: 8 },
        children: () =>
          todos.value.map((todo: TodoItem) =>
            view({
              key: todo.id,
              style: {
                flexDirection: 'row',
                alignItems: 'center',
                backgroundColor: 'white',
                padding: 15,
                borderRadius: 8,
                borderLeftWidth: 4,
                borderLeftColor: todo.done ? '#4CAF50' : '#FFC107',
              },
              children: [
                touchableOpacity({
                  onPress: () => toggleTodo(todo.id),
                  style: { flex: 1 },
                  children: text({
                    style: {
                      fontSize: 16,
                      textDecorationLine: todo.done ? 'line-through' : 'none',
                      color: todo.done ? '#9E9E9E' : '#333',
                    },
                    children: todo.text,
                  }),
                }),
                touchableOpacity({
                  onPress: () => removeTodo(todo.id),
                  style: {
                    backgroundColor: '#f44336',
                    paddingHorizontal: 12,
                    paddingVertical: 6,
                    borderRadius: 4,
                  },
                  children: text({
                    style: { color: 'white', fontSize: 14 },
                    children: '✕',
                  }),
                }),
              ],
            })
          ),
      }),
    ],
  });
}

/**
 * Main App Component
 */
function App(): RNMountFunction {
  return scrollView({
    style: { flex: 1, backgroundColor: '#fff' },
    contentContainerStyle: { padding: 20 },
    children: [
      // Header
      view({
        style: {
          marginBottom: 30,
          alignItems: 'center',
        },
        children: [
          text({
            style: {
              fontSize: 32,
              fontWeight: 'bold',
              color: '#1976D2',
            },
            children: '🌀 Rasen',
          }),
          text({
            style: {
              fontSize: 16,
              color: '#666',
              marginTop: 5,
            },
            children: 'React Native Example',
          }),
        ],
      }),

      // Counter Example
      CounterExample(),

      // Todo Example
      TodoExample(),

      // Info Section
      view({
        style: {
          padding: 20,
          backgroundColor: '#FFF3E0',
          borderRadius: 10,
        },
        children: [
          text({
            style: {
              fontSize: 18,
              fontWeight: 'bold',
              color: '#E65100',
              marginBottom: 10,
            },
            children: 'About This Example',
          }),
          text({
            style: {
              fontSize: 14,
              color: '#666',
              lineHeight: 22,
            },
            children:
              "This example demonstrates Rasen's reactive rendering system with React Native. " +
              "It uses Vue's reactivity system (@vue/reactivity) for state management and " +
              "directly interfaces with React Native's Fabric architecture.",
          }),
        ],
      }),
    ],
  });
}

/**
 * Entry point - mount the app to React Native root
 *
 * @param rootTag - The React Native root view tag
 * @returns Unmount function
 */
export function createApp(rootTag: number): () => void {
  return mount(App(), rootTag);
}

// Default export for React Native AppRegistry compatibility
export default App;
